# Первый этап: сборка
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Второй этап: продакшн образ
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install ci --only=production

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE ${PORT}

CMD ["npm", "run", "start:prod"]
